/**
 * Parser for Lightspeed "Tarte Market / Tarte Beach House" end-of-day
 * PDFs (generated by Looker / Kounta and attached to the email that
 * lands in accounts@tarte.com.au each morning).
 *
 * The report has three sections:
 *   1. Revenue per site (Total Ex Tax / Total Inc Tax)
 *   2. Total Reporting Group Sales (list of categories)
 *   3. Reporting Group Breakdown — per site, per category, top 10
 *      products by quantity, shown side-by-side
 *
 * Rather than hand-roll a PDF text parser (Looker's layout uses floating
 * text runs that ruin column alignment), we pass the PDF to Claude and
 * ask it to extract structured JSON. This keeps the parser resilient to
 * minor layout shifts.
 */

import Anthropic from "@anthropic-ai/sdk"
import Decimal from "decimal.js"

export interface LightspeedTopProduct {
  name: string
  quantity: number
}

export interface LightspeedCategory {
  categoryName: string
  topProducts: LightspeedTopProduct[]
}

export interface LightspeedSite {
  siteName: string // e.g. "Tarte Market", "Tarte Beach House"
  totalExTax: Decimal
  totalIncTax: Decimal
  categories: LightspeedCategory[]
}

export interface LightspeedPdfReport {
  /** YYYY-MM-DD — the single trading day the report covers. */
  reportDate: string | null
  sites: LightspeedSite[]
}

const EXTRACTION_PROMPT = `Extract all the data from this Lightspeed / Kounta end-of-day report.

Return valid JSON only, no other text or markdown fences:
{
  "reportDate": "YYYY-MM-DD or null",
  "sites": [
    {
      "siteName": "exact site name as on the report, e.g. Tarte Market",
      "totalExTax": number,
      "totalIncTax": number,
      "categories": [
        {
          "categoryName": "exact reporting group name, e.g. Alcohol, Cafe Food, Coffee & Tea",
          "topProducts": [
            { "name": "exact product name", "quantity": integer }
          ]
        }
      ]
    }
  ]
}

Important:
- The report covers a single trading day ("Sale Closed Date is in the last 1 complete day").
  reportDate is that day in YYYY-MM-DD format (i.e. the day BEFORE the "Generated on" footer).
- This report covers THREE Tarte venues. Look for and include ALL of them:
    1. "Tarte Burleigh" — appears as "Tarte Pty Ltd" in the top Revenue
       table, but as "Tarte Burleigh" in the per-site breakdown header.
       Always emit siteName: "Tarte Burleigh" for this venue (use the
       breakdown name, not the legal entity name).
    2. "Tarte Beach House"
    3. "Tarte Market"
  These appear in BOTH the Revenue section at the top AND in the per-site
  Reporting Group Breakdown sections lower down. Cross-reference:
  Revenue-table "Tarte Pty Ltd" = breakdown-header "Tarte Burleigh" — same
  site, two labels. Merge them into ONE entry with siteName "Tarte Burleigh"
  containing both the totals AND the breakdown categories.
  Never skip a venue because it's thin on data — if needed, return it with
  categories: [] and the totals from the Revenue table.
- Include every reporting group / category shown in the per-site breakdown section,
  even if it has zero products listed.
- For each category, list the top products with their quantity, in the order shown.
- Skip duplicate "(Copy)" sections — e.g. ignore "Coffee & Tea (Copy)" if
  "Coffee & Tea" is already there.
- Strip trailing ellipsis (...) and trailing periods from category names and product
  names — e.g. "Iced Latte." becomes "Iced Latte", "Coffee & Tea ..." becomes "Coffee & Tea".
- totalExTax and totalIncTax are the site-level revenue totals from the first
  section ("Revenue"). Parse $14,769.41 style strings as 14769.41.
- If a field cannot be determined, use null.`

export async function parseLightspeedPdf(
  pdfBuffer: Buffer
): Promise<LightspeedPdfReport> {
  const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

  const response = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 8192,
    // Belt-and-braces JSON-only enforcement. Sonnet sometimes opens with
    // "Looking at this report..." which then fails JSON.parse — observed
    // 2026-04-27 on a real EOD email. The system prompt + the leading "{"
    // assistant turn together force the response to start with valid JSON
    // and contain nothing else.
    system:
      "You are a strict JSON extractor. Output ONLY a single JSON object — no preamble, no commentary, no markdown fences. Your entire response must be valid JSON that can be passed directly to JSON.parse.",
    messages: [
      {
        role: "user",
        content: [
          {
            type: "document",
            source: {
              type: "base64",
              media_type: "application/pdf",
              data: pdfBuffer.toString("base64"),
            },
          },
          { type: "text", text: EXTRACTION_PROMPT },
        ],
      },
      {
        // Prefilling the assistant turn with "{" makes Claude continue
        // mid-JSON; we re-prepend the brace before parsing.
        role: "assistant",
        content: "{",
      },
    ],
  })

  const textBlock = response.content.find((b) => b.type === "text")
  if (!textBlock || textBlock.type !== "text") {
    throw new Error("No text response from Claude API")
  }

  // Strip code fences if any leaked through, and recover from "Looking at
  // this report..." style preambles by extracting the outermost {...}.
  let jsonStr = ("{" + textBlock.text).trim()
  if (jsonStr.startsWith("```")) {
    jsonStr = jsonStr.replace(/^```(?:json)?\n?/, "").replace(/\n?```$/, "")
  }
  if (!jsonStr.startsWith("{")) {
    const first = jsonStr.indexOf("{")
    const last = jsonStr.lastIndexOf("}")
    if (first >= 0 && last > first) {
      jsonStr = jsonStr.slice(first, last + 1)
    }
  }

  interface RawSite {
    siteName: string
    totalExTax: number | string | null
    totalIncTax: number | string | null
    categories: Array<{
      categoryName: string
      topProducts: Array<{ name: string; quantity: number }>
    }>
  }
  interface RawParsed {
    reportDate: string | null
    sites: RawSite[]
  }

  const parsed = JSON.parse(jsonStr) as RawParsed

  if (!Array.isArray(parsed.sites)) {
    throw new Error("Invalid parse: sites is not an array")
  }

  return {
    reportDate: parsed.reportDate,
    sites: parsed.sites.map((s) => ({
      siteName: s.siteName,
      totalExTax: new Decimal(s.totalExTax ?? 0),
      totalIncTax: new Decimal(s.totalIncTax ?? 0),
      categories: (s.categories ?? []).map((c) => ({
        categoryName: c.categoryName,
        topProducts: (c.topProducts ?? [])
          .filter((p) => p.name && typeof p.quantity === "number")
          .map((p) => ({ name: p.name, quantity: p.quantity })),
      })),
    })),
  }
}
