/**
 * Import recipe ingredient linkages from Chef Notepad scraped data.
 *
 * This populates PreparationItem and DishComponent rows using the scraped
 * chefnotepad-recipes.json file (generated by the browser scraper).
 *
 * It also updates each Preparation's yield values (yieldQuantity, yieldUnit,
 * yieldWeightGrams) from the real Chef Notepad data.
 *
 * Usage:
 *   npx tsx scripts/import-recipe-ingredients.ts
 *   npx tsx scripts/import-recipe-ingredients.ts --dry-run   (no DB writes)
 *
 * Safe to re-run — clears existing items for each matched recipe before
 * inserting, so you always end up with a clean state.
 *
 * After running: click "Recalculate All Costs" in the app, or run:
 *   npx tsx scripts/recalculate-all.ts
 */
import "dotenv/config"
import { PrismaClient } from "../src/generated/prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"
import { Pool } from "pg"
import { readFileSync } from "fs"
import { resolve } from "path"
import Decimal from "decimal.js"

const DRY_RUN = process.argv.includes("--dry-run")

// ── Unit normalisation ───────────────────────────────────────────────────────
// Maps Chef Notepad units → Tarte Kitchen recipe units
const UNIT_MAP: Record<string, string> = {
  g: "g", gram: "g",
  kg: "kg", kilogram: "kg",
  ml: "ml", milliliter: "ml", millilitre: "ml",
  l: "l", L: "l", liter: "l", litre: "l",
  ea: "ea", each: "ea",
  dozen: "dozen",
  piece: "ea", piece: "ea",
  slice: "ea",
  bunch: "ea",    // 1 bunch = 1 ea (gramsPerUnit handles the weight conversion)
  punnet: "ea",
  bag: "ea",
  carton: "ea",
  tray: "ea",
  portion: "serve",
  serv: "serve",
  serving: "serve",
  serve: "serve",
}

// ── Yield unit → DB format ───────────────────────────────────────────────────
const YIELD_UNIT_MAP: Record<string, string> = {
  gram: "g", kilogram: "kg",
  milliliter: "ml", millilitre: "ml", liter: "l", litre: "l",
  each: "ea", piece: "ea", tub: "ea",
  portion: "serve", serving: "serve",
}

function toYieldUnit(cnUnit: string): string {
  return YIELD_UNIT_MAP[cnUnit] ?? cnUnit
}

function toRecipeUnit(cnUnit: string): string {
  return UNIT_MAP[cnUnit] ?? cnUnit
}

/** Estimate total weight in grams for a batch yield */
function toYieldWeightGrams(qty: number, cnUnit: string): number {
  switch (cnUnit) {
    case "gram":       return qty
    case "kilogram":   return qty * 1000
    case "milliliter":
    case "millilitre": return qty          // 1ml ≈ 1g for liquids
    case "liter":
    case "litre":      return qty * 1000
    case "each":
    case "piece":
    case "tub":        return qty * 100    // placeholder: 100g per unit
    case "portion":
    case "serving":    return qty * 150    // placeholder: 150g per serve
    default:           return qty          // fallback
  }
}

// ── Name matching helpers ────────────────────────────────────────────────────

/** Strip common suffixes added in Chef Notepad recipe names */
function normaliseName(name: string): string {
  return name
    .replace(/ Recipe$/i, "")
    .replace(/ - Recipe$/i, "")
    .replace(/ \(recipe\)$/i, "")
    .trim()
    .toLowerCase()
}

function bestMatch<T extends { name: string }>(
  cnName: string, items: T[]
): T | null {
  const norm = normaliseName(cnName)
  // 1. Exact (case-insensitive, suffix-stripped)
  const exact = items.find((i) => i.name.toLowerCase() === norm || i.name.toLowerCase() === cnName.toLowerCase())
  if (exact) return exact
  // 2. DB name contains CN name
  const contains = items.find((i) => i.name.toLowerCase().includes(norm))
  if (contains) return contains
  // 3. CN name contains DB name (only if DB name is long enough)
  const contained = items.find((i) => i.name.length > 4 && norm.includes(i.name.toLowerCase()))
  if (contained) return contained
  return null
}

// ── Types ────────────────────────────────────────────────────────────────────
type CNIngredient = {
  qty: number
  unit: string
  name: string
  isSubRecipe: boolean
  isIngredient: boolean
  refId: string | null
}
type CNRecipe = {
  id: string
  name: string
  cost: number
  sellingPrice: number
  category: string
  yieldQty: number
  yieldUnit: string
  ingredients: CNIngredient[]
}

async function main() {
  const pool = new Pool({ connectionString: process.env.DATABASE_URL })
  const adapter = new PrismaPg(pool)
  const db = new PrismaClient({ adapter })

  if (DRY_RUN) console.log("🔍  DRY RUN — no DB writes\n")

  const cnRecipes: CNRecipe[] = JSON.parse(
    readFileSync(resolve("/Users/chris/Downloads/chefnotepad-recipes.json"), "utf-8")
  )
  console.log(`📂  Loaded ${cnRecipes.length} recipes from Chef Notepad\n`)

  // Pre-load all DB entities
  const dbPreps = await db.preparation.findMany({ select: { id: true, name: true } })
  const dbDishes = await db.dish.findMany({ select: { id: true, name: true } })
  const dbIngredients = await db.ingredient.findMany({ select: { id: true, name: true } })

  console.log(`🗄   DB: ${dbPreps.length} preparations, ${dbDishes.length} dishes, ${dbIngredients.length} ingredients\n`)

  let prepItemsCreated = 0
  let dishCompsCreated = 0
  let prepYieldsUpdated = 0
  const unmatchedRecipes: string[] = []
  const unmatchedIngredients: string[] = []

  // Separate CN recipes into preparations (no selling price) and dishes (have price)
  const cnPreps = cnRecipes.filter((r) => r.sellingPrice === 0)
  const cnDishes = cnRecipes.filter((r) => r.sellingPrice > 0)

  console.log(`📋  Chef Notepad: ${cnPreps.length} preparations, ${cnDishes.length} dishes\n`)
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n")

  // ── Process Preparations ─────────────────────────────────────────────────
  console.log("🍳  PREPARATIONS\n")
  for (const cn of cnPreps) {
    const dbPrep = bestMatch(cn.name, dbPreps)
    if (!dbPrep) {
      unmatchedRecipes.push(`PREP: "${cn.name}"`)
      continue
    }

    const yieldUnit = toYieldUnit(cn.yieldUnit)
    const yieldWeightGrams = toYieldWeightGrams(cn.yieldQty, cn.yieldUnit)
    const costPerGram = yieldWeightGrams > 0 ? cn.cost / yieldWeightGrams : 0
    const costPerServe = cn.yieldQty > 0 ? cn.cost / cn.yieldQty : 0

    if (!DRY_RUN) {
      // Update yield + cost on the preparation
      await db.preparation.update({
        where: { id: dbPrep.id },
        data: {
          yieldQuantity: cn.yieldQty,
          yieldUnit,
          yieldWeightGrams,
          batchCost: cn.cost,
          costPerGram: new Decimal(costPerGram).toDecimalPlaces(6).toNumber(),
          costPerServe: new Decimal(costPerServe).toDecimalPlaces(4).toNumber(),
        },
      })
      // Clear existing items
      await db.preparationItem.deleteMany({ where: { preparationId: dbPrep.id } })
    }
    prepYieldsUpdated++

    // Create items
    let sortOrder = 0
    for (const ing of cn.ingredients) {
      const unit = toRecipeUnit(ing.unit)
      if (unit === ing.unit && !Object.values(UNIT_MAP).includes(unit)) {
        unmatchedIngredients.push(`  Unit "${ing.unit}" in "${cn.name}" → "${ing.name}" (kept as-is)`)
      }

      if (ing.isSubRecipe) {
        const dbSubPrep = bestMatch(ing.name, dbPreps)
        if (!dbSubPrep) {
          unmatchedIngredients.push(`  SUB-PREP not found: "${ing.name}" (in "${cn.name}")`)
          continue
        }
        if (!DRY_RUN) {
          await db.preparationItem.create({
            data: {
              preparationId: dbPrep.id,
              subPreparationId: dbSubPrep.id,
              quantity: ing.qty,
              unit,
              sortOrder: sortOrder++,
            },
          })
        }
        prepItemsCreated++
      } else {
        const dbIng = bestMatch(ing.name, dbIngredients)
        if (!dbIng) {
          unmatchedIngredients.push(`  INGREDIENT not found: "${ing.name}" (in "${cn.name}")`)
          continue
        }
        if (!DRY_RUN) {
          await db.preparationItem.create({
            data: {
              preparationId: dbPrep.id,
              ingredientId: dbIng.id,
              quantity: ing.qty,
              unit,
              sortOrder: sortOrder++,
            },
          })
        }
        prepItemsCreated++
      }
    }

    console.log(`  ✅  "${dbPrep.name}" → ${cn.ingredients.length} items, yield: ${cn.yieldQty} ${yieldUnit}`)
  }

  console.log("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n")

  // ── Process Dishes ───────────────────────────────────────────────────────
  console.log("🍽️   DISHES\n")
  for (const cn of cnDishes) {
    const dbDish = bestMatch(cn.name, dbDishes)
    if (!dbDish) {
      unmatchedRecipes.push(`DISH: "${cn.name}"`)
      continue
    }

    if (!DRY_RUN) {
      // Update cost + selling price derived fields
      const sellingPriceExGst = new Decimal(cn.sellingPrice).div(1.1)
      const fcPct = sellingPriceExGst.gt(0)
        ? new Decimal(cn.cost).div(sellingPriceExGst).mul(100)
        : new Decimal(0)
      const gp = sellingPriceExGst.minus(cn.cost)

      await db.dish.update({
        where: { id: dbDish.id },
        data: {
          sellingPrice: cn.sellingPrice,
          sellingPriceExGst: sellingPriceExGst.toDecimalPlaces(2).toNumber(),
          totalCost: cn.cost,
          foodCostPercentage: fcPct.toDecimalPlaces(1).toNumber(),
          grossProfit: gp.toDecimalPlaces(2).toNumber(),
        },
      })
      // Clear existing components
      await db.dishComponent.deleteMany({ where: { dishId: dbDish.id } })
    }

    // Create components
    let sortOrder = 0
    for (const ing of cn.ingredients) {
      const unit = toRecipeUnit(ing.unit)

      if (ing.isSubRecipe) {
        const dbPrep = bestMatch(ing.name, dbPreps)
        if (!dbPrep) {
          unmatchedIngredients.push(`  SUB-PREP not found: "${ing.name}" (in dish "${cn.name}")`)
          continue
        }
        if (!DRY_RUN) {
          await db.dishComponent.create({
            data: {
              dishId: dbDish.id,
              preparationId: dbPrep.id,
              quantity: ing.qty,
              unit,
              sortOrder: sortOrder++,
            },
          })
        }
        dishCompsCreated++
      } else {
        const dbIng = bestMatch(ing.name, dbIngredients)
        if (!dbIng) {
          unmatchedIngredients.push(`  INGREDIENT not found: "${ing.name}" (in dish "${cn.name}")`)
          continue
        }
        if (!DRY_RUN) {
          await db.dishComponent.create({
            data: {
              dishId: dbDish.id,
              ingredientId: dbIng.id,
              quantity: ing.qty,
              unit,
              sortOrder: sortOrder++,
            },
          })
        }
        dishCompsCreated++
      }
    }

    console.log(`  ✅  "${dbDish.name}" → ${cn.ingredients.length} components  $${cn.sellingPrice}`)
  }

  // ── Summary ──────────────────────────────────────────────────────────────
  console.log("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
  console.log("\n📊  Summary")
  console.log(`   Preparation yields updated: ${prepYieldsUpdated}`)
  console.log(`   PreparationItems created:   ${prepItemsCreated}`)
  console.log(`   DishComponents created:     ${dishCompsCreated}`)
  console.log(`   Unmatched recipes:          ${unmatchedRecipes.length}`)
  console.log(`   Unmatched ingredients:      ${unmatchedIngredients.length}`)

  if (unmatchedRecipes.length > 0) {
    console.log("\n⚠️   Unmatched recipes (need manual linking in app):")
    unmatchedRecipes.forEach((r) => console.log("  " + r))
  }

  if (unmatchedIngredients.length > 0) {
    console.log("\n⚠️   Unmatched ingredients/sub-preps:")
    unmatchedIngredients.slice(0, 30).forEach((r) => console.log(r))
    if (unmatchedIngredients.length > 30) {
      console.log(`  ... and ${unmatchedIngredients.length - 30} more`)
    }
  }

  if (!DRY_RUN) {
    console.log("\n⚡️  Next: run recalculate-all.ts (or click Recalculate All Costs in the app)\n")
  }

  await db.$disconnect()
  await pool.end()
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
